### ISSUE TITLE
Adding Pronote for liberte BKO

### ISSUE THREAD

**Issue by alfus5** [Adloya/PronotePlus#1]
Please add compatibility for [this pronote URL](http://196.200.57.210:8080/pronote/eleve.html?fd=1)

**Comment by Adloya** [comment]
I am working on it 👍

**Comment by alfus5** [comment]
thanks

**Comment by Adloya** [comment]
Hi,

Is the "LIBERTE" a real school or is it a RP or something like that.
If it is the latter, can you give me some creditentials for testing ? (If it's a real school, I would not recommend you to give your creditentials)
If you can't give me creditentials, I will try to add Pronote+ without them.

Thanks

**Comment by alfus5** [comment]
No it's a real school but I don't want to give my passwords, etc to person on the net

**Comment by Adloya** [comment]
Normally it's fixed, tell me if it isn't.
